### ISSUE TITLE
init fails for Integer hash keys

### ISSUE THREAD

**Issue by jico** [jico/automata#1]
Typical automaton alphabets are binary strings. We'd like to be able to specify alphabets and transitions with integers in our YAML file, for example:

```
alphabet:
  - 0
  - 1
transitions:
  q1:
    0: q2
    1: q3
```

However, we pass Strings as input to our DFA (i.e. `dfa.accepts?('01101')`), so calling `@transitions[head][symbol]` where symbol is a string, fails.
